version: '2'
services:
  node1:
    image: svenkreiss/shoveling-worker
    container_name: node1
    hostname: node1
    volumes:
     - ./worker/supervisord/consul-server.conf:/etc/supervisor/conf.d/consul-server.conf
    ports:
     - "5060:5060"
     - "8500:8500"
     - "8600:8600"
     - "8600:8600/udp"
  node2:
    image: svenkreiss/shoveling-worker
    container_name: node2
    hostname: node2
    volumes:
     - ./worker/supervisord/consul.conf:/etc/supervisor/conf.d/consul.conf
    ports:
     - "5061:5060"
    depends_on:
     - node1
