version: '2'
services:
  interactive:
    image: svenkreiss/shoveling
    container_name: interactive
    hostname: interactive
    volumes:
     - ./image/supervisord/consul-server.conf:/etc/supervisor/conf.d/consul-server.conf
     - ./image/consul/services/shoveling.json:/opt/consul/services/shoveling.json
     #- ./image/supervisord/mysql.conf:/etc/supervisor/conf.d/mysql.conf
     - ./image/consul/services/mysql.json:/opt/consul/services/mysql.json
    ports:
     - "5060:5060"
     - "8500:8500"
     - "8600:8600"
     - "8600:8600/udp"
    command: bash -c "service mysql start && supervisord -n -c /etc/supervisor/supervisord.conf"
  node1:
    image: svenkreiss/shoveling
    container_name: node1
    hostname: node1
    volumes:
     - ./image/supervisord/consul.conf:/etc/supervisor/conf.d/consul.conf
     - ./image/consul/services/shoveling.json:/opt/consul/services/shoveling.json
    ports:
     - "5061:5060"
    depends_on:
     - interactive
  node2:
    image: svenkreiss/shoveling
    container_name: node2
    hostname: node2
    volumes:
     - ./image/supervisord/consul.conf:/etc/supervisor/conf.d/consul.conf
     - ./image/consul/services/shoveling.json:/opt/consul/services/shoveling.json
    ports:
     - "5062:5060"
    depends_on:
     - interactive
  node3:
    image: svenkreiss/shoveling
    container_name: node3
    hostname: node3
    volumes:
     - ./image/supervisord/consul.conf:/etc/supervisor/conf.d/consul.conf
     - ./image/consul/services/shoveling.json:/opt/consul/services/shoveling.json
    ports:
     - "5063:5060"
    depends_on:
     - interactive
