version: '2'
services:
  node1:
    image: svenkreiss/shoveling-worker
    container_name: node1
    ports:
     - "5000:5000"
    command: bash -c "./worker && /bin/consul agent -node=node1 -data-dir /opt/consul -server -bootstrap-expect 1"
  node2:
    image: svenkreiss/shoveling-worker
    container_name: node2
    command: bash -c "./worker && /bin/consul agent -node=node2 -data-dir /opt/consul -join node1"
    depends_on:
     - node1
